[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && uvicorn app:create_fastapi_app --factory --host 0.0.0.0 --port $PORT" 